name: Build Documentation

on:
 repository_dispatch:  # This is used to trigger the flow from Npgsql/EFCore.PG via HTTP POST
 push:
    branches:
      - master  # We don't want branches in doc to trigger builds

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    # Checkout all repos
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        path: docs
        fetch-depth: 1
    - name: Checkout live docs repo
      uses: actions/checkout@v2
      with:
        repository: npgsql/livedocs
        path: docs/live
    - name: Clear live docs repo
      run: rm -rf live/*
    - name: Checkout Npgsql
      uses: actions/checkout@v2
      with:
        repository: npgsql/npgsql
        path: docs/Npgsql
    - name: Checkout EFCore.PG
      uses: actions/checkout@v2
      with:
        repository: npgsql/Npgsql.EntityFrameworkCore.PostgreSQL
        path: docs/EFCore.PG

    # Setup software
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Get mono
      run: |
        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt-get update
        sudo apt-get install mono-complete --yes
    - name: Get docfx
      run: |
        curl -L https://github.com/dotnet/docfx/releases/latest/download/docfx.zip -o docfx.zip
        unzip -d .docfx docfx.zip

    # Build
    - name: Build docs
      run:  mono .docfx/docfx.exe
    - name: Commit and push
      run: |
        export GIT_COMMITTER_NAME=$(git show -s --format='%cn')
        export GIT_COMMITTER_EMAIL=$(git show -s --format='%ce')
        export GIT_AUTHOR_NAME=$(git show -s --format='%an')
        export GIT_AUTHOR_EMAIL=$(git show -s --format='%ae')
        export COMMIT_HASH=$(git show -s --format='%H')
        export SUBJECT=$(git show -s --format='%s')
        cd live
        git add .
        git commit -m "$SUBJECT" -m "Original commit: $COMMIT_HASH"
        header=$(echo -n "ad-m:${{ secrets.DOC_MGMT_TOKEN }}" | base64)
        git -c http.extraheader="AUTHORIZATION: basic $header" push origin HEAD:master
